version: '3.5'

services:
  app:
    image: node:16-alpine
    working_dir: /app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: development
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./docker/mongo/init:/docker-entrypoint-initdb.d
      - ./docker/data/mongo/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:pass@mongo:27017/"
    depends_on:
      - mongo